---
# My Ansible playbook.
- hosts: all

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install required packages
      apt: 
        pkg:
          - zsh
          - nginx
          - postgresql
        state: present
