---
- hosts: target
  become: yes
  tasks:
  - name: ensure nginx is at the latest version
    apt: name=nginx state=latest
    become: yes

  - name: start nginx
    service:
      name: nginx
      state: started
    become: yes

  - name: copy the nginx config file and restart nginx
    copy:
      src: reverse_proxy.cfg
      dest: /etc/nginx/sites-available/reverse_proxy.cfg
    become: yes

  - name: create symlink
    file:
      src: /etc/nginx/sites-available/reverse_proxy.cfg
      dest: /etc/nginx/sites-enabled/default
      state: link
    become: yes

  - name: restart nginx
    service:
      name: nginx
      state: restarted
    become: yes

  - name: install certbot
    apt: name=certbot state=latest
    become: yes

  - name: install certbot nginx
    apt: name=python3-certbot-nginx state=latest
    become: yes
