version: '2'
services:

  db:
    image: postgres:10.10
    environment:
      - POSTGRES_USER=workout
      - POSTGRES_PASSWORD=workout
      - POSTGRES_DB=workout
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432

  web:
    image: t0lia/workout:latest
    environment:
    - DATABASE_URL=db:5432
    - DATABASE_USER=workout
    - DATABASE_PASSWORD=workout
    - DB=workout
    ports:
      - 8080:8080
    expose:
      - 8080
    links:
      - db

#  ui:
#    image: t0lia/workoutui:latest
#    ports:
#      - 8081:8080
#    expose:
#      - 8081
#    links:
#      - rest
